name: carbine
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.9.0
  mobile_scanner: ^3.5.1
  qr_flutter: ^4.1.0
  intl: ^0.18.1
  numpad_layout: ^0.0.3
  flutter_animate: ^4.5.2
  http: ^1.3.0
  lottie: ^3.3.1
  flutter_speed_dial: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/fedimint.png
    - assets/animations/lightning.json
