name: Android Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/android-build
        with:
          mode: release
          with-signing: true
          android-keystore: ${{ secrets.ANDROID_KEYSTORE }}
          keystore-password: ${{ secrets.KEYSTORE_PASSWORD }}
          key-password: ${{ secrets.KEY_PASSWORD }}
          key-alias: ${{ secrets.KEY_ALIAS }}

      - name: Upload to Release
        uses: ncipollo/release-action@v1
        with:
          tag: latest
          name: "Latest Android Release"
          artifacts: build/app/outputs/flutter-apk/*.apk
          allowUpdates: true
          replacesArtifacts: true
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
