name: Android Release

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/android-build
        with:
          mode: release
          use-production-package-id: ${{ startsWith(github.ref, 'refs/tags/') }}
          with-signing: true
          android-keystore: ${{ secrets.ANDROID_KEYSTORE }}
          keystore-password: ${{ secrets.KEYSTORE_PASSWORD }}
          key-password: ${{ secrets.KEY_PASSWORD }}
          key-alias: ${{ secrets.KEY_ALIAS }}

      - name: Upload to Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'latest' }}
          name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || 'Latest Android Release' }}
          artifacts: build/app/outputs/flutter-apk/*.apk
          allowUpdates: true
          replacesArtifacts: true
          draft: false
          prerelease: ${{ !startsWith(github.ref, 'refs/tags/v') || contains(github.ref, 'rc') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
