name: Android Debug

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/android-build
        with:
          mode: debug
